# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0003_auto_20160428_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericoption',
            old_name='nombre',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='genericoption',
            old_name='valor',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='genericparentoption',
            name='genericfield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options_type', to='genericform.GenericField'),
        ),
    ]
