# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0004_auto_20160428_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericform.GenericForm')),
            ],
        ),
    ]
