# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0005_genericformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfield',
            name='verbose_name',
            field=models.CharField(max_length=60),
        ),
    ]
