# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0006_auto_20160429_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=150)),
                ('numero_mesa', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='genericfield',
            options={'ordering': ('ordinal',)},
        ),
        migrations.AlterModelOptions(
            name='genericform',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterModelOptions(
            name='genericformdata',
            options={'verbose_name': 'Reporte de formulario', 'verbose_name_plural': 'Reportes de formularios'},
        ),
        migrations.AlterModelOptions(
            name='genericoption',
            options={'ordering': ('ordinal',)},
        ),
        migrations.AddField(
            model_name='genericoption',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genericfield',
            name='type',
            field=models.IntegerField(choices=[(1, b'TEXTO_SOLO_NUMEROS_ENTEROS'), (2, b'TEXTO_SOLO_DECIMALES'), (3, b'TEXTO_SOLO_LETRAS'), (4, b'TEXTO_SOLO_LETRAS_Y_NUMEROS'), (5, b'TEXTO_SOLO_LETRAS_CON_ESPACIOS'), (6, b'TEXTO_SOLO_LETRAS_Y_NUMEROS_CON_ESPACIOS'), (7, b'TEXTO_SOLO_LETRAS_Y_NUMEROS_CON_ESPACIOS_Y_SIMBOLOS'), (8, b'SELECCIONABLE_TEXTO'), (9, b'PUNTO_GEOREFERENCIADO')]),
        ),
        migrations.AlterField(
            model_name='genericform',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericform.Mesa'),
        ),
    ]
