# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0007_auto_20170530_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoption',
            name='label',
            field=models.CharField(max_length=30),
        ),
    ]
