# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericform', '0010_auto_20170601_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfield',
            name='verbose_name',
            field=models.CharField(max_length=200),
        ),
    ]
